export const invoiceTemplate = `
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; margin: 0; padding: 40px; color: #333; }
        .header { display: flex; justify-content: space-between; margin-bottom: 40px; border-bottom: 2px solid #eee; padding-bottom: 20px; }
        .logo { max-height: 80px; }
        .invoice-title { font-size: 32px; font-weight: bold; color: #2c3e50; }
        .meta-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 40px; }
        .box { background: #f9f9f9; padding: 20px; border-radius: 8px; }
        .box h3 { margin-top: 0; color: #555; }
        .table-container { margin-bottom: 40px; }
        table { width: 100%; border-collapse: collapse; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
        th { background: #f5f5f5; color: #555; }
        .total-row { font-size: 1.2em; font-weight: bold; background: #eef; }
        .footer { margin-top: 60px; text-align: center; color: #888; font-size: 12px; border-top: 1px solid #eee; padding-top: 20px; }
        .photo-section { margin-top: 20px; text-align: center; }
        .photo-section img { max-width: 100%; max-height: 300px; border: 1px solid #ccc; border-radius: 4px; }
    </style>
</head>
<body>
    <div class="header">
        <div>
            {{#if orgLogoUrl}}
            <img src="{{orgLogoUrl}}" class="logo" alt="Logo">
            {{/if}}
            <div style="margin-top: 10px; font-weight: bold;">{{orgName}}</div>
            <div style="font-size: 12px; color: #666;">{{{orgAddress}}}</div>
        </div>
        <div style="text-align: right;">
            <div class="invoice-title">INVOICE</div>
            <div>#{{invoiceNumber}}</div>
            <div>Date: {{generatedDate}}</div>
        </div>
    </div>

    <div class="meta-grid">
        <div class="box">
            <h3>Bill To</h3>
            <div><strong>Broker/Facility:</strong> {{brokerName}}</div>
            <div><strong>Load #:</strong> {{loadNumber}}</div>
            <div><strong>BOL #:</strong> {{bolNumber}}</div>
            <div><strong>Location:</strong> {{facilityAddress}}</div>
        </div>
        <div class="box">
            <h3>Detention Details</h3>
            <div><strong>Arrived:</strong> {{startTime}}</div>
            <div><strong>Departed:</strong> {{endTime}}</div>
            <div><strong>Total Duration:</strong> {{totalDuration}}</div>
        </div>
    </div>

    <div class="table-container">
        <table>
            <thead>
                <tr>
                    <th>Description</th>
                    <th>Rate</th>
                    <th>Hours</th>
                    <th style="text-align: right;">Amount</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Detention Charge (excess of free time)</td>
                    <td>\${{ratePerHour}}/hr</td>
                    <td>{{payableHours}} hrs</td>
                    <td style="text-align: right;">\${{totalDue}}</td>
                </tr>
                <tr class="total-row">
                    <td colspan="3" style="text-align: right;">Total Due</td>
                    <td style="text-align: right;">\${{totalDue}}</td>
                </tr>
            </tbody>
        </table>
    </div>

    {{#if photoUrl}}
    <div class="photo-section">
        <h3>Proof of Detention</h3>
        <img src="{{photoUrl}}" alt="Detention Evidence">
        <p style="font-size: 12px; color: #666;">Photo taken at: {{photoTime}}</p>
    </div>
    {{/if}}

    <div class="footer">
        <p>Thank you for your business.</p>
        <p>Generated by TruckMate</p>
    </div>
</body>
</html>
`;
