
import { PDFDocument, rgb, StandardFonts } from 'https://cdn.skypack.dev/pdf-lib';

interface DispatcherSheetData {
    rateConId: string;
    brokerName?: string;
    stops: any[];
    dispatchInstructions: any[];
    loadId?: string;
}

/**
 * Generates the Dispatcher Sheet PDF
 */
export async function generateDispatchSheetPDF(data: DispatcherSheetData): Promise<Uint8Array> {
    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage();
    const { width, height } = page.getSize();
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    const fontSize = 12;
    const lineHeight = 15;
    let y = height - 50;

    // --- Header ---
    page.drawText('Dispatcher Sheet', { x: 50, y, size: 20, font: boldFont });
    y -= 30;

    // --- Load Info ---
    page.drawText(`Load Ref: ${data.rateConId}`, { x: 50, y, size: fontSize, font });
    y -= lineHeight;
    page.drawText(`Broker: ${data.brokerName || 'N/A'}`, { x: 50, y, size: fontSize, font });
    y -= lineHeight * 2;

    // --- Stops ---
    page.drawText('Stops:', { x: 50, y, size: 14, font: boldFont });
    y -= lineHeight;

    if (data.stops && data.stops.length > 0) {
        // Ensure sorted by sequence
        const sortedStops = [...data.stops].sort((a: any, b: any) => a.sequence_number - b.sequence_number);

        sortedStops.forEach((stop: any) => {
            const stopType = stop.stop_type || 'Stop';
            const address = stop.address || 'N/A';

            page.drawText(`${stop.sequence_number}. ${stopType}: ${address}`, { x: 50, y, size: 10, font });
            y -= lineHeight;

            if (stop.scheduled_arrival) {
                const arrival = new Date(stop.scheduled_arrival).toLocaleString();
                page.drawText(`   Arrival: ${arrival}`, { x: 50, y, size: 10, font });
                y -= lineHeight;
            }
        });
    } else {
        page.drawText('No stops found.', { x: 50, y, size: 10, font });
    }
    y -= lineHeight;

    // --- Dispatch Instructions ---
    page.drawText('Dispatch Instructions:', { x: 50, y, size: 14, font: boldFont });
    y -= lineHeight;

    const instructions = data.dispatchInstructions || [];
    if (instructions.length > 0) {
        instructions.forEach((inst: any) => {
            // Check for page break
            if (y < 50) {
                const newPage = pdfDoc.addPage();
                y = newPage.getSize().height - 50;
            }

            const title = inst.title_en || 'Instruction';
            page.drawText(`- ${title}`, { x: 50, y, size: 11, font: boldFont });
            y -= lineHeight;

            if (inst.description_en) {
                // Very basic truncation/wrapping logic
                // For a robust template, one might want to split lines
                const cleanDesc = inst.description_en.replace(/\n/g, ' ');
                const desc = cleanDesc.substring(0, 90) + (cleanDesc.length > 90 ? '...' : '');
                page.drawText(`  ${desc}`, { x: 50, y, size: 10, font });
                y -= lineHeight;
            }
            y -= 5;
        });
    } else {
        page.drawText('No specific special instructions.', { x: 50, y, size: 10, font });
        y -= lineHeight;
    }

    // Example Footer or additional info
    y -= lineHeight;
    page.drawText('Generated by TruckMate', { x: 50, y: 30, size: 8, font, color: rgb(0.5, 0.5, 0.5) });

    return await pdfDoc.save();
}
