// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXg4RrM0dCMec1fqqJA2vpBN2izeQ3bss',
    appId: '1:804258523004:web:e49fdefaddae1b16',
    messagingSenderId: '804258523004',
    projectId: 'drmtm-79897',
    authDomain: 'drmtm-79897.firebaseapp.com',
    databaseURL: 'https://drmtm-79897.firebaseio.com',
    storageBucket: 'drmtm-79897.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9F7d2ilbx89Z0W4UsXud77V6kpnrAlC4',
    appId: '1:804258523004:android:449b5d60181de42f2266f9',
    messagingSenderId: '804258523004',
    projectId: 'drmtm-79897',
    databaseURL: 'https://drmtm-79897.firebaseio.com',
    storageBucket: 'drmtm-79897.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqltYE8CHwZ2ysfhPEGJudOhbGkVnuxaI',
    appId: '1:804258523004:ios:b1870901369c15222266f9',
    messagingSenderId: '804258523004',
    projectId: 'drmtm-79897',
    databaseURL: 'https://drmtm-79897.firebaseio.com',
    storageBucket: 'drmtm-79897.firebasestorage.app',
    iosBundleId: 'com.truckmate.truckMateApp',
  );
}
